sonar.projectKey=et-soc1-pmic
sonar.qualitygate.wait=false
sonar.cfamily.compile-commands=compile_commands.json
sonar.cfamily.cache.enabled=false
sonar.sourceEncoding=utf-8
sonar.python.version=3.9, 3.10, 3.11, 3.12, 3.13
sonar.cfamily.build-wrapper-output=build_wrapper_output_directory
sonar.exclusions=dock.py,build**,AtmelStudio/**,scripts/**,common/ThirdParty/**
sonar.sources=.
